---
flightdeck_web_default_vhost_envvars:
  - name: "T7_SITE_ENVIRONMENT"
    value: "{{ lookup('env', 'T7_SITE_ENVIRONMENT') | default('docker-dev', true) }}"

flightdeck_web_default_vhosts:
  - name: "{{ lookup('env', 'APACHE_SITE_NAME') | default('docker.test', true) }}"
    host: "*:80"
    docroot: "{{ lookup('env', 'APACHE_DOCROOT_DIR') | default('/var/www/html', true )}}"
    aliases: "{{ lookup('env', 'APACHE_SITE_ALIAS') | default(['docker.localhost'], true) }}"
    env: "{{ flightdeck_web_default_vhost_envvars }}"
  - name: "{{ lookup('env', 'APACHE_SITE_NAME') | default('docker.test', true) }}"
    host: "*:443"
    docroot: "{{ lookup('env', 'APACHE_DOCROOT_DIR') | default('/var/www/html', true )}}"
    aliases: "{{ lookup('env', 'APACHE_SITE_ALIAS') | default(['docker.localhost'], true) }}"
    env: "{{ flightdeck_web_default_vhost_envvars }}"
    https:  yes
    certFile: "/etc/ssl/apache2/server.pem"
    keyFile: "/etc/ssl/apache2/server.key"

flightdeck_web_defaults:
  vhosts: "{{ flightdeck_web_default_vhosts }}"
  php:
    sendmail_path: "{{ lookup('env', 'PHP_SENDMAIL_PATH') | default('/usr/sbin/sendmail', true) }}"
    max_execution_time: "{{ lookup('env', 'PHP_MAX_EXEC_TIME') | default('120', true) }}"
    max_input_vars: "{{ lookup('env', 'PHP_MAX_INPUT_VARS') | default('3000', true) }}"
    memory_limit: "{{ lookup('env', 'PHP_MAX_INPUT_VARS') | default('320M', true) }}"
    upload_max_filesize: "128M"
    post_max_size: "128M"
    error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
    display_errors: no
    display_startup_errors: no
    error_log: "/dev/stderr"
    variables_order: "GPCS"
    opcache_enable: yes
    opcache_validate_timestamps: yes
    opcache_revalidate_freq: '60'
    opcache_max_accelerated_files: '20000'
    opcache_memory_consumption: '192'
    opcache_interned_strings_buffer: '16'
    opcache_fast_shutdown: yes
  xdebug:
    enabled: "{{ lookup('env', 'PHP_XDEBUG_ENABLED') | default(false, true) | bool }}"
    autostart: "{{ lookup('env', 'PHP_XDEBUG_AUTOSTART') | default(false, true) | bool }}"
    connectBack: "{{ lookup('env', 'PHP_XDEBUG_REMOTE_CONNECT_BACK') | default(false, true) | bool }}"
    stdoutLogs: "{{ lookup('env', 'PHP_XDEBUG_STDOUT_LOGS') | default(false, true) }}"
    remoteHost: "{{ lookup('env', 'PHP_XDEBUG_REMOTE_HOST') | default('10.254.254.254', true) }}"
    port: "9000"
    idekey: "PHPSTORM"
  xdebugProfile:
    trigger: "{{ lookup('env', 'PHP_XDEBUG_PROFILE_TRIGGER') }}"
    force: no

flightdeck_web: flightdeck_web_defaults
